name: BarnyWhitelist
version: 1.0.0
main: sk.meldiron.barlywhitelist.Main
authors: [Meldiron]
api-version: 1.13
#depend: [API]

#commands:
#  command:
#    aliases: [cmd]
#    description: Command Command
